### ISSUE TITLE
请问您的数据集UCIHand能开源吗？

### ISSUE THREAD

**Issue by yy2yy** [HowieMa/CPM_Pytorch#2]
请问您用的数据集UCIHand能开源吗？非常希望能看到您的回复。

**Comment by HowieMa** [comment]
抱歉，这个暂时不行。后期如果会开源会第一时间告知你，谢谢！

**Comment by HowieMa** [comment]
@yy2yy 我已经在我NSRM那个repo中release了预处理后的panoptic dataset, 您可以使用那个。另外这个code已经很久远了，使用起来可能会有一些问题。请关注我NSRM那个repo中的CPM，谢谢！

**Comment by yy2yy** [comment]
> @yy2yy 我已经在我NSRM那个repo中release了预处理后的panoptic dataset, 您可以使用那个。另外这个code已经很久远了，使用起来可能会有一些问题。请关注我NSRM那个repo中的CPM，谢谢！

谢谢您的回复，我测试了您的CPM和NSRM，自己训练的模型，测试了下发现CPM提取的关键点比NSRM提取的关键点准确呢？请问能开源一下NSRM的模型供测试一下吗？非常感谢

**Comment by HowieMa** [comment]
@yy2yy 谢谢您的提问，已在nsrmhand 里开源了模型，以及我训练时用的裁剪过的手的图片。如果为了公平比较，建议使用NSRM代码里的CPM。我们现在讨论的这个repo中的CPM的一些细节，比如每个stage 的kernel size 都和NSRMhand 中的CPM不一样。我Nsrm里用的cpm是参照openpose - hand 中 caffe 版本的CPM写的，请见 [openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/models/hand/pose_deploy.prototxt)。
他们这个hand CPM跟CPM原始论文中的模型细节上有点不同。您可以仔细对比一下两个repo 中cpm.py 的区别。

另外，NSRM要比CPM难训练很多，因为NSRM 开始的若干个 epoch都侧重在训练limb 那部分，limb loss 和 keypoint loss 的权重比也会随着epoch数的增加而改变。让后期的epoch 侧重在keypoint loss上。相比之下，CPM确实收敛的更快。如果epoch不够多的话，会出现CPM更好的情况。
